# This is a basic workflow to automate build process with Actions
name: build & push on prod

on:
  push:
    branches: [master]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check-out repository
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      # Install project
      - name: Install project
        run: npm install

      # Build project
      - name: Build project
        run: npm run build:prod

      # Push to prod branch
      - name: Push to prod
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # Build directory to deploy
          build_dir: dist
          target_branch: prod
          commit_message: generated build for deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
